name: Bearer

on:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bearer Scan
        uses: bearer/bearer-action@v2
        with:
          scanner: secrets,sast
          exit-code: 1
          diff: true
          path: .